/* global window */
// Sample student data — varied personas so templates don't all feel like the same person.

const PERSONAS = {
  designer: {
    name: "Lina Marchetti",
    role: "Graphic Design — 3rd year",
    school: "Politecnico di Milano",
    location: "Milan, IT",
    pronouns: "she/her",
    tagline: "Books, posters, type. Currently obsessed with woodblock printing.",
    email: "lina.m@uni.it",
    socials: ["are.na/lina", "instagram/linamarc", "linkedin/linamarchetti"],
    now: [
      "Drawing a display serif for a poetry chapbook",
      "Reading: Bringhurst, The Elements of Typographic Style",
      "Slowly learning Cinema 4D on weekends",
    ],
    projects: [
      { title: "Atelier 21", kind: "Identity", year: "2025", note: "Visual system for a ceramics studio. Print, signage, web." },
      { title: "Forme & Volume", kind: "Editorial", year: "2024", note: "Quarterly typography zine, 96pp." },
      { title: "Notturno", kind: "Type design", year: "2024", note: "Display serif drawn for a poetry collection." },
      { title: "Civic Atlas", kind: "Infographic", year: "2023", note: "Wayfinding map for Brera district." },
      { title: "Untitled Press", kind: "Risograph", year: "2023", note: "Series of six A2 posters for a music festival." },
      { title: "Vento", kind: "Packaging", year: "2023", note: "Olive oil packaging for a Sicilian co-op. 4 SKUs." },
    ],
    experience: [
      { role: "Design intern", org: "Studio Mut", time: "Summer 2025", note: "Identity & print, two campaigns." },
      { role: "Freelance", org: "Various", time: "2023–", note: "Posters & books for student clients." },
      { role: "Studio assistant", org: "Atelier Carvalho-Bernau", time: "2023", note: "Three-week residency in Berlin." },
    ],
    education: [
      { degree: "BFA Communication Design", org: "Politecnico di Milano", time: "2022–25" },
      { degree: "Erasmus exchange", org: "ENSCI Paris", time: "Spring 2024" },
      { degree: "Liceo Artistico", org: "Brera, Milan", time: "2017–22" },
    ],
    skills: ["InDesign", "Glyphs", "Risograph", "Letterpress", "After Effects", "HTML/CSS"],
    awards: [
      { name: "ADCI Bronze · Student Editorial", year: "2024" },
      { name: "Type@Cooper · Honourable Mention", year: "2024" },
      { name: "Politecnico Merit Scholarship", year: "2023" },
    ],
    writing: [
      { title: "Why I still print my mockups", where: "Are.na blog", year: "2025" },
      { title: "Notes from a residency in Berlin", where: "Personal site", year: "2023" },
    ],
    testimonials: [
      { quote: "Lina has the rarest thing: patience for the small decisions. Her books are better for it.", author: "Prof. Elena Rosi, Politecnico di Milano" },
      { quote: "We hired Lina for two weeks and she stayed for two months. She'll be a great designer.", author: "Studio Mut, summer mentor" },
    ],
    languages: ["Italian (native)", "English (C1)", "French (B2)", "German (A2)"],
  },

  developer: {
    name: "Jordan Park",
    role: "Computer Science — final year",
    school: "University of Waterloo",
    location: "Toronto, CA",
    pronouns: "they/them",
    tagline: "Distributed systems, weird shells, and tiny compilers.",
    email: "jpark@uwaterloo.ca",
    socials: ["github/jpark", "x/jpark_dev", "linkedin/jordanpark"],
    now: [
      "Writing a B-tree storage engine in Rust",
      "Reading: Designing Data-Intensive Applications",
      "Mentoring two first-years through their first PRs",
    ],
    projects: [
      { title: "tinyk8s", kind: "Open source", year: "2025", note: "A 1.4k-line container orchestrator for teaching." },
      { title: "lex.fish", kind: "CLI", year: "2024", note: "Lexer DSL with REPL & coverage maps." },
      { title: "ferro-db", kind: "Database", year: "2024", note: "Embedded KV store written in Rust." },
      { title: "campusbus", kind: "Mobile", year: "2023", note: "Live shuttle tracker for 8k students." },
      { title: "shellboard", kind: "Tooling", year: "2023", note: "TUI dashboard for Linux servers. Go + bubbletea." },
      { title: "uwflow-mirror", kind: "Service", year: "2022", note: "Course schedule scraper, runs on a Raspberry Pi." },
    ],
    experience: [
      { role: "Software intern", org: "Stripe", time: "Summer 2025", note: "Payments orchestration team, Go." },
      { role: "Research asst", org: "WatSys Lab", time: "2024–25", note: "Storage benchmarking for SSDs." },
      { role: "Software intern", org: "Shopify", time: "Summer 2024", note: "Internal tools, Ruby + React." },
      { role: "TA — CS 246", org: "University of Waterloo", time: "2023–", note: "Object-oriented programming in C++." },
    ],
    education: [
      { degree: "BSc Computer Science", org: "University of Waterloo", time: "2021–26" },
      { degree: "Exchange", org: "ETH Zürich", time: "Fall 2024" },
    ],
    skills: ["Go", "Rust", "Python", "Postgres", "Kubernetes", "Linux", "gRPC", "TypeScript"],
    awards: [
      { name: "President's Scholarship of Distinction", year: "2021" },
      { name: "Hack the North · Best Use of Cloudflare", year: "2024" },
      { name: "WICS Open Source Award", year: "2024" },
    ],
    writing: [
      { title: "tinyk8s: what 1,400 lines teaches you about Kubernetes", where: "jpark.dev", year: "2025" },
      { title: "A storage engine that fits in your head", where: "WatSys blog", year: "2025" },
      { title: "I rewrote my dotfiles. Was it worth it?", where: "jpark.dev", year: "2024" },
    ],
    testimonials: [
      { quote: "Jordan writes the kind of small, careful code that's easy to debug at 3am. I'd hire them anywhere.", author: "Eng manager, Stripe" },
      { quote: "One of the strongest students I've supervised in five years. Already operating like a junior engineer.", author: "Prof. R. Kim, WatSys Lab" },
    ],
    languages: ["English (native)", "Korean (fluent)", "French (A2)"],
  },

  business: {
    name: "Amara Okonkwo",
    role: "Business & Strategy — MSc",
    school: "HEC Paris",
    location: "Paris, FR",
    pronouns: "she/her",
    tagline: "Operator turned strategist. Marketplaces, growth, ops at scale.",
    email: "a.okonkwo@hec.edu",
    socials: ["linkedin/aokonkwo", "substack/amara", "x/amara_ok"],
    now: [
      "Researching mobile-money rails for the dissertation",
      "Co-organizing the HEC × LBS Africa Business Conf",
      "Reading: The Fish That Ate the Whale, Cohan",
    ],
    projects: [
      { title: "Mercado Brief", kind: "Newsletter", year: "2025", note: "Weekly read on African marketplaces. 4.2k subs." },
      { title: "Hawker GTM", kind: "Consulting", year: "2024", note: "Go-to-market for a Lagos logistics startup." },
      { title: "Founders Studio", kind: "Community", year: "2024", note: "Co-organized a 60-person founder retreat." },
      { title: "RideShare West Africa", kind: "Research", year: "2023", note: "60-page market scan, 14 operators, 3 countries." },
      { title: "HEC Africa Club", kind: "Leadership", year: "2024–", note: "VP of programming. 320 members." },
    ],
    experience: [
      { role: "Strategy intern", org: "Bain & Co.", time: "Summer 2025", note: "Retail & consumer practice." },
      { role: "Ops associate", org: "Lori Systems", time: "2022–23", note: "Logistics startup, Lagos." },
      { role: "Analyst", org: "Endeavor Nigeria", time: "2021–22", note: "Founder selection, post-investment support." },
      { role: "Teaching asst", org: "HEC Paris", time: "2024–", note: "Strategic Management I, MSc cohort." },
    ],
    education: [
      { degree: "MSc Strategic Management", org: "HEC Paris", time: "2024–26" },
      { degree: "BA Economics", org: "University of Lagos", time: "2019–22" },
      { degree: "Summer school", org: "LSE, London", time: "2022" },
    ],
    skills: ["Strategy", "Financial modeling", "Market research", "SQL", "Notion", "French (B2)"],
    awards: [
      { name: "HEC Excellence Scholarship", year: "2024" },
      { name: "Endeavor MVP — Most Valuable Analyst", year: "2022" },
      { name: "UniLag First-Class Honours", year: "2022" },
    ],
    writing: [
      { title: "What Lagos taught me about pricing", where: "Mercado Brief", year: "2025" },
      { title: "Why marketplaces fail in West Africa", where: "Mercado Brief", year: "2024" },
      { title: "Notes on operating in a 30-warehouse network", where: "Substack", year: "2023" },
    ],
    testimonials: [
      { quote: "Amara has the rare combination of operator's instinct and analytical patience.", author: "Olawale O., COO, Lori Systems" },
      { quote: "Her Mercado Brief is the most-shared newsletter in my circle. She sees what others miss.", author: "Subscriber, Lagos VC partner" },
    ],
    languages: ["English (native)", "Igbo (fluent)", "French (B2)", "Yoruba (B1)"],
  },

  mark_holloway: {
    key: "mark_holloway",
    name: "Mark Holloway",
    pronouns: "he/him",
    field: "Sport & Exercise Science",
    year: "BSc · Final Year",
    institution: "Loughborough University",
    faculty: "School of Sport, Exercise and Health Sciences",
    specialization: "Football performance & rehab",
    currentRole: "S&C Intern · Leicester City U19",
    location: "Loughborough, UK",
    email: "m.holloway@lboro.ac.uk",
    phone: "+44 7700 900 412",
    url: "mark.portfolio-cv.online",
    dob: "21 Mar 2002",
    height: "184 cm",
    weight: "79 kg",
    sportPlayed: "Football · RB · semi-pro 2018–22",
    initials: "MH",
    tagline: "Performance, data, and bodies that keep showing up.",
    summary: "Final-year sports scientist building injury-resistant footballers. I work with GPS, force plates, and a clipboard. I write code on rest days.",
    coached: [
      { squad: "Leicester City U19", period: "2024 — present", n: 22, role: "S&C Intern",
        outcomes: [{ stat: "+6%", label: "mean CMJ over 16wks" }, { stat: "88%", label: "squad hit velocity ceiling" }, { stat: "1.4×", label: "weekly tonnage vs baseline" }],
        note: "First academy squad to fully adopt VBT for compounds." },
      { squad: "Burton Albion U17", period: "2023 — 24", n: 18, role: "Performance Analyst",
        outcomes: [{ stat: "−41%", label: "hamstring injury YoY" }, { stat: "11", label: "GPS reports / wk delivered" }],
        note: "Designed and rolled out Nordic-progression protocol." },
      { squad: "Individual · UCL Round-of-16", period: "Summer 2024", n: 1, role: "Off-season prep coach",
        outcomes: [{ stat: "12.4", label: "wk return-to-play" }, { stat: "−0.04s", label: "10m split vs pre-season" }],
        note: "Anonymised at player request." },
      { squad: "Loughborough Women's 5-a-side", period: "2022 — present", n: 14, role: "Volunteer head coach",
        outcomes: [{ stat: "2×", label: "city-league finals" }, { stat: "0", label: "soft-tissue injuries '24" }],
        note: "Weekly community sessions, no budget, no excuses." },
    ],
    research: [
      { title: "Sprint exposure and soft-tissue injury risk in adolescent footballers", venue: "Journal of Sports Sciences", status: "Under review", role: "Co-author (2nd)", year: 2026 },
      { title: "GPS load asymmetry across U17–U19 academy systems", venue: "BASES Student Conference", status: "Published", role: "First author", year: 2025 },
      { title: "ForceDecks asymmetry as a return-to-play gate", venue: "Loughborough · BSc Dissertation", status: "In progress", role: "Author · Supervisor: Prof. R. Whitmore", year: 2026 },
    ],
    certs: [
      { name: "UEFA C License", body: "The FA · UEFA", year: "2025", status: "Active" },
      { name: "NSCA CSCS", body: "NSCA", year: "Aug 2026", status: "In prep" },
      { name: "BLS Provider", body: "Resus Council UK", year: "2025", status: "Active" },
      { name: "Catapult OpenField — Certified User", body: "Catapult Sports", year: "2024", status: "Active" },
      { name: "VALD ForceDecks Operator", body: "VALD", year: "2024", status: "Active" },
      { name: "Smartabase — Basic", body: "Smartabase", year: "2025", status: "Active" },
    ],
    experience: [
      { role: "Strength & Conditioning Intern", org: "Leicester City · U19 Academy", period: "2024 — present",
        bullets: ["Daily prep, on-field warm-ups, post-match readiness scoring (22 players).", "Catapult OpenField pipeline, R-based reporting weekly to head coach.", "Co-designed return-to-play gating with academy physios."] },
      { role: "Performance Analyst", org: "Burton Albion · U17 Academy", period: "2023 — 24",
        bullets: ["GPS data cleaning + match reports, Notion dashboards for staff.", "Built Nordic progression doc adopted by U15 and U17."] },
      { role: "Athletic Trainer", org: "Loughborough Lightning · Basketball Academy", period: "2022 — 23",
        bullets: ["General prep + rehab support across two age groups.", "First contact with force-plate testing."] },
      { role: "Floor Coach", org: "Loughborough Strength Co.", period: "2021 — 22",
        bullets: ["Programmed and ran sessions for 30+ general-population clients.", "Paid my own tuition with it."] },
    ],
    skills: {
      tech: [
        { name: "Catapult OpenField", level: 5 },
        { name: "VALD ForceDecks", level: 5 },
        { name: "Smartabase", level: 4 },
        { name: "Polar Team Pro", level: 4 },
        { name: "R · tidyverse, mixed models", level: 4 },
        { name: "Python · pandas, scikit-learn", level: 3 },
        { name: "SQL · Postgres", level: 3 },
        { name: "Notion · operational dashboards", level: 5 },
        { name: "Tableau", level: 3 },
      ],
      practical: ["Force-velocity profiling (Samozino)", "YoYo IR1 / IR2 testing", "Wingate · 30s anaerobic", "Cooper test · field VO₂", "Isokinetic ham/quad ratio", "Movement screen (FMS+)", "Manual therapy basics", "Periodisation · block + conjugate"],
    },
    languages: [
      { name: "English", level: "Native", cefr: "C2" },
      { name: "Spanish", level: "Upper-Intermediate", cefr: "B2" },
      { name: "German", level: "Intermediate", cefr: "B1" },
    ],
    education: [
      { degree: "BSc Sport & Exercise Science", org: "Loughborough University · School of Sport, Exercise and Health Sciences", period: "2022 — 26", notes: "Dissertation: ForceDecks asymmetry as a return-to-play gate." },
      { degree: "Erasmus+ Semester · Movement Sciences", org: "KU Leuven, Belgium", period: "Spring 2024", notes: "Coursework: biomechanics, motor control, statistics." },
      { degree: "A-Levels · Biology · PE · Mathematics", org: "Loughborough Grammar School", period: "2018 — 22", notes: "A*AA. Captain, 1st XI football." },
    ],
    awards: [
      { name: "Vice-Chancellor's Excellence Scholarship", org: "Loughborough Univ.", year: "2023, 2024" },
      { name: "2nd place · BASES Student Research", org: "BASES", year: "2025" },
      { name: "Athlete-Student of the Year (nominee)", org: "Loughborough Univ.", year: "2024" },
    ],
    media: [
      { kind: "YouTube", name: "Linear Sprint Lab", meta: "biweekly · 1.2k subs", url: "youtube.com/@linearsprintlab" },
      { kind: "Newsletter", name: "Load & Recover", meta: "412 subs · every other Tuesday", url: "loadandrecover.substack.com" },
      { kind: "Community", name: "Loughborough Women's 5-a-side · Volunteer coach", meta: "weekends, 14 players", url: "—" },
    ],
    season: "2025/26",
    headlineStats: [
      { value: "55", label: "Athletes coached" },
      { value: "1,412", label: "GPS sessions logged" },
      { value: "−41%", label: "Hamstring injuries" },
      { value: "6", label: "Certifications" },
    ],
  },
};

const DEFAULT_PERSONA = PERSONAS.designer;

window.PERSONAS = PERSONAS;
window.DEFAULT_PERSONA = DEFAULT_PERSONA;
