/* global window */
// Faculty / department groups + personas per group.
// Extends window.PERSONAS with the 5 new student profiles we need
// (existing 3 cover Tech/Business/Creative).

const NEW_PERSONAS = {
  // Law & Politics
  law: {
    name: "Endrit Kabashi",
    role: "Drejtësi — viti i tretë",
    faculty: "Fakulteti Juridik",
    group: "law",
    school: "Universiteti i Prishtinës",
    location: "Pristina, XK",
    pronouns: "he/him",
    tagline: "Constitutional law, human rights, and the quiet work of writing good arguments.",
    email: "endrit.k@uni-pr.edu",
    socials: ["linkedin/ekabashi", "ssrn/kabashi", "twitter/endrit_law"],
    now: [
      "Drafting a memo on the new property registry reform",
      "Reading: Dworkin, Law's Empire",
      "Moot court prep for the Vis Vienna semifinals",
    ],
    projects: [
      { title: "Case Note: Spahija v. Kosovo", kind: "Case comment", year: "2025", note: "Published in the student review. 18pp on Article 6 ECHR." },
      { title: "Civic Tracker", kind: "Legal-tech", year: "2024", note: "Open-source database of municipal council votes, 4 cities." },
      { title: "Moot Court — Vis Vienna", kind: "Competition", year: "2024", note: "Quarterfinals · best respondent memorandum, team of 4." },
      { title: "Pro bono clinic", kind: "Legal aid", year: "2024–", note: "8 cases on tenancy and family law for the legal aid clinic." },
      { title: "Constitutional Notes", kind: "Newsletter", year: "2025", note: "Weekly read on courts in the Balkans. 1.1k subs." },
    ],
    experience: [
      { role: "Legal intern", org: "Boga & Associates", time: "Summer 2025", note: "Commercial litigation team. Tirana." },
      { role: "Research asst", org: "Constitutional Court of Kosovo", time: "2024", note: "Constitutional Review Department, ten-week placement." },
      { role: "Pro bono clinic", org: "Legal Aid Kosovo", time: "2024–", note: "Tenancy and family law cases under supervision." },
    ],
    education: [
      { degree: "LL.B. Drejtësi", org: "Universiteti i Prishtinës", time: "2023–26" },
      { degree: "Exchange — European Law", org: "Università di Bologna", time: "Spring 2025" },
    ],
    skills: ["Constitutional law", "ECHR practice", "Legal drafting", "Comparative method", "Albanian (native)", "EU regs"],
    awards: [
      { name: "Vis Vienna · Best Respondent Memo", year: "2024" },
      { name: "Faculty Merit Scholarship", year: "2024" },
      { name: "Civic Tech Award · Kosovo Open Data", year: "2024" },
    ],
    writing: [
      { title: "Article 6 ECHR in the Balkans", where: "Pristina Law Review", year: "2025" },
      { title: "Reading the Property Registry Reform", where: "Constitutional Notes", year: "2025" },
      { title: "Notes from a moot", where: "Personal blog", year: "2024" },
    ],
    testimonials: [
      { quote: "Endrit writes the cleanest first draft of any student I've supervised. He thinks in paragraphs, not sentences.", author: "Prof. A. Krasniqi, Universiteti i Prishtinës" },
      { quote: "On the Vis team he ran the respondent side — careful, prepared, never theatrical. Exactly what an advocate should be.", author: "Coach, Vis Vienna 2024" },
    ],
    languages: ["Albanian (native)", "English (C2)", "Italian (B2)", "German (A2)"],
  },

  // Medical & Healthcare
  med: {
    name: "Dr. Era Hoxha",
    role: "Mjekësi — viti i pestë",
    faculty: "Fakulteti i Mjekësisë",
    group: "med",
    school: "Universiteti i Mjekësisë, Tiranë",
    location: "Tirana, AL",
    pronouns: "she/her",
    tagline: "Internal medicine bound. Currently rotating through cardiology and learning to slow down.",
    email: "era.hoxha@umed.al",
    socials: ["linkedin/erahoxha", "researchgate/EraHoxha", "twitter/dr_era_h"],
    now: [
      "Rotating through cardiology at QSUT — Tirana",
      "Reading: Harrison's Internal Medicine, 21st ed.",
      "USMLE Step 1 prep — exam booked September",
    ],
    projects: [
      { title: "Rural ECG Study", kind: "Research", year: "2025", note: "Screened 320 patients in Mat district. First author, manuscript in review." },
      { title: "Tirana Med Society", kind: "Leadership", year: "2024–", note: "VP of programming · 220 student members · 12 events / yr." },
      { title: "MedEd Notes", kind: "Newsletter", year: "2024", note: "Albanian-language clinical review summaries. 2.4k subs across the region." },
      { title: "Free clinic", kind: "Volunteer", year: "2023–", note: "Bi-monthly clinic for uninsured patients, organized with two attendings." },
    ],
    experience: [
      { role: "Cardiology rotation", org: "QSUT Tirana", time: "Spring 2026", note: "Inpatient · CCU · cath lab observation." },
      { role: "Internal medicine rotation", org: "Spitali Amerikan", time: "Fall 2025", note: "Wards, 8 weeks. Mentor: Dr. B. Hysa." },
      { role: "Research asst", org: "UMT Cardiology Lab", time: "2024–25", note: "ECG screening study, 320-patient cohort." },
    ],
    education: [
      { degree: "MD candidate", org: "Universiteti i Mjekësisë, Tiranë", time: "2021–27" },
      { degree: "Erasmus exchange", org: "Charité — Berlin", time: "Spring 2025" },
    ],
    skills: ["Clinical reasoning", "ECG interpretation", "Patient interviewing", "BLS / ACLS", "STATA / R", "Suturing"],
    awards: [
      { name: "UMT Excellence in Clinical Skills", year: "2025" },
      { name: "Erasmus + Mobility Grant", year: "2025" },
      { name: "Tirana Med Society Service Award", year: "2024" },
    ],
    writing: [
      { title: "ECG findings in rural Albania", where: "Albanian Med Journal (in review)", year: "2025" },
      { title: "How to read a Holter monitor", where: "MedEd Notes", year: "2025" },
      { title: "Notes from my first rotation", where: "Personal blog", year: "2024" },
    ],
    testimonials: [
      { quote: "Era is the most prepared student on my service. She writes notes the way I wish my residents would.", author: "Dr. B. Hysa, Internal Medicine attending" },
      { quote: "On the rural ECG study she ran the field logistics for 320 patients and the data was clean. Future internist, no doubt.", author: "Prof. M. Berisha, UMT Cardiology" },
    ],
    languages: ["Albanian (native)", "English (C2)", "Italian (C1)", "German (B1)"],
  },

  // Creative & Media — film/video
  film: {
    name: "Noor Tariq",
    role: "Film & Video — final year",
    faculty: "Fakulteti i Media Digjitale / Multimedia",
    group: "creative",
    school: "Sarajevo Film Academy",
    location: "Sarajevo, BA",
    pronouns: "she/her",
    tagline: "Documentary first. Editor by trade, director by accident. Currently cutting a short on a Bosnian river town.",
    email: "noor.t@sfa.edu",
    socials: ["vimeo/noortariq", "instagram/noor.tariq.film", "imdb/nm12345"],
    now: [
      "Cutting 'Drina' — a 14-minute documentary short",
      "Reading: Murch, In the Blink of an Eye",
      "Saving for a used Sony FX3",
    ],
    projects: [
      { title: "Drina", kind: "Short documentary", year: "2025", note: "14-min observational film on a town along the river. In post." },
      { title: "Brace", kind: "Music video", year: "2024", note: "Single-take video for indie band Lëkura. 380k plays." },
      { title: "The Tailor of Baščaršija", kind: "Short documentary", year: "2024", note: "9-min portrait. Selected at three regional festivals." },
      { title: "Ledra", kind: "Color & edit", year: "2023", note: "Editor + colorist on a 22-min student feature. Sarajevo FF selection." },
    ],
    experience: [
      { role: "Edit asst", org: "Pristina Films", time: "Summer 2025", note: "Assisted lead editor on a feature documentary." },
      { role: "Freelance editor", org: "Various", time: "2022–", note: "Music videos, short docs, commissions." },
      { role: "Festival programming intern", org: "Sarajevo Film Festival", time: "Summer 2024", note: "Short film selection committee." },
    ],
    education: [
      { degree: "BFA Film Direction", org: "Sarajevo Film Academy", time: "2022–26" },
      { degree: "Erasmus exchange", org: "FAMU, Prague", time: "Spring 2025" },
    ],
    skills: ["DaVinci Resolve", "Premiere Pro", "Sound design", "Cinematography", "Color grading", "Producing"],
    awards: [
      { name: "Sarajevo FF · Best Student Short", year: "2024" },
      { name: "Albanian Cinema Days · Honourable Mention", year: "2024" },
      { name: "FAMU exchange merit grant", year: "2025" },
    ],
    writing: [
      { title: "Notes on a slow cut", where: "Filmskool zine", year: "2025" },
      { title: "Editing 'Tailor of Baščaršija'", where: "Personal blog", year: "2024" },
    ],
    testimonials: [
      { quote: "Noor edits the way good writers write — knowing when to leave the silence in.", author: "Prof. A. Bajraktari, Sarajevo Film Academy" },
      { quote: "She delivered the cut a week early and it was already better than my notes.", author: "Lëkura, band on 'Brace' music video" },
    ],
    languages: ["Bosnian (native)", "English (C2)", "Urdu (heritage)", "French (B1)"],
  },

  // Education & Social Sciences
  edu: {
    name: "Klara Selimi",
    role: "Psikologji — viti i dytë master",
    faculty: "Fakulteti i Psikologjisë",
    group: "edu",
    school: "Universiteti i Tiranës",
    location: "Tirana, AL",
    pronouns: "she/her",
    tagline: "Adolescent mental health, school-based interventions, and trying to do research that actually reaches kids.",
    email: "k.selimi@unitir.edu.al",
    socials: ["linkedin/klaraselimi", "osf/klara-s", "twitter/klara_psy"],
    now: [
      "Writing the master's thesis on social anxiety in Albanian adolescents",
      "Reading: Yalom, The Gift of Therapy",
      "Volunteering at a hotline two evenings a week",
    ],
    projects: [
      { title: "Tirana Adolescent Study", kind: "Research", year: "2025", note: "Mixed-methods study, 220 high schoolers across 4 schools." },
      { title: "Notebook Notes", kind: "Writing", year: "2024", note: "Bi-monthly column on therapy in plain Albanian. 3.1k subs." },
      { title: "Mentorship Pilot", kind: "Field program", year: "2024", note: "Co-led a 10-week pilot mentorship program with 22 students." },
      { title: "Coding the DSM", kind: "Tool", year: "2023", note: "A small DSM-5-TR cross-reference for students, in Albanian." },
    ],
    experience: [
      { role: "Research asst", org: "UT Dept of Psychology", time: "2024–", note: "Adolescent anxiety lab. Data collection + analysis." },
      { role: "Hotline volunteer", org: "Linja e Këshillimit", time: "2023–", note: "Two evenings a week, trained in CBT-informed crisis support." },
      { role: "Teaching asst", org: "UT — Intro Psychology", time: "2024–25", note: "Recitations for 80 first-year undergraduates." },
    ],
    education: [
      { degree: "MSc Clinical Psychology", org: "Universiteti i Tiranës", time: "2024–26" },
      { degree: "BSc Psychology", org: "Universiteti i Tiranës", time: "2020–23" },
    ],
    skills: ["Clinical interviewing", "R / SPSS", "Qualitative coding (NVivo)", "Group facilitation", "CBT-informed counseling", "Psychoeducation"],
    awards: [
      { name: "UT Best Thesis Proposal (MSc)", year: "2025" },
      { name: "Albanian Psych Association · Student Paper", year: "2024" },
      { name: "Erasmus + Mobility Grant", year: "2024" },
    ],
    writing: [
      { title: "Loneliness in 17-year-olds", where: "Albanian Journal of Psychology", year: "2025" },
      { title: "What CBT is, plainly", where: "Notebook Notes", year: "2025" },
      { title: "On not over-diagnosing teenagers", where: "Notebook Notes", year: "2024" },
    ],
    testimonials: [
      { quote: "Klara is a thorough researcher and the rare grad student who reads the news as well as the journal.", author: "Prof. E. Dervishi, UT Psychology" },
      { quote: "On the hotline she is calm and present. She'll be a real clinician.", author: "Hotline supervisor, Linja e Këshillimit" },
    ],
    languages: ["Albanian (native)", "English (C1)", "Italian (B2)"],
  },

  // Sports
  sport: {
    name: "Marko Vulić",
    role: "Sports Science — final year",
    faculty: "Fakulteti i Sportit / Kulturës Fizike",
    group: "sport",
    school: "Univerzitet u Beogradu — Sport",
    location: "Belgrade, RS",
    pronouns: "he/him",
    tagline: "Sprint coaching, return-to-play, and reading more sports science than my coach wants me to.",
    email: "marko.vulic@sport.edu.rs",
    socials: ["instagram/marko.coach", "linkedin/markovulic", "stridelab.youtube"],
    now: [
      "Coaching three U17 sprinters through the indoor season",
      "Reading: Verkhoshansky, Supertraining (again)",
      "Building a Notion playbook for hamstring rehab",
    ],
    projects: [
      { title: "Hamstring RTP protocol", kind: "Coaching tool", year: "2025", note: "10-stage return-to-play protocol used by 6 clubs in Belgrade." },
      { title: "U17 sprint program", kind: "Coaching", year: "2024–", note: "3 athletes; one PR'd at nationals in 100m." },
      { title: "Stridelab", kind: "YouTube channel", year: "2023–", note: "Short videos on sprint mechanics, 4.6k subs." },
      { title: "Performance dashboard", kind: "Tool", year: "2024", note: "Notion dashboard the club uses for monitoring." },
    ],
    experience: [
      { role: "Sprint coach asst", org: "AK Crvena Zvezda", time: "2024–", note: "Junior squad, alongside head sprint coach." },
      { role: "Research asst", org: "Belgrade Sport Lab", time: "2024", note: "Force plate and HSR data for senior team." },
      { role: "Strength coach intern", org: "FK Partizan Youth", time: "Summer 2024", note: "U15 squad, 8-week placement." },
    ],
    education: [
      { degree: "BSc Sports Science", org: "Univerzitet u Beogradu", time: "2022–26" },
      { degree: "Exchange", org: "Norges Idrettshøgskole · Oslo", time: "Fall 2024" },
    ],
    skills: ["S&C programming", "GPS data (Catapult)", "Force plate analysis", "Notion / Smartabase", "Sprint biomechanics", "First aid / EMR"],
    awards: [
      { name: "Best Undergraduate Thesis (Belgrade Sport)", year: "2025" },
      { name: "UEFA C licence", year: "2024" },
      { name: "Erasmus + Mobility Grant", year: "2024" },
    ],
    writing: [
      { title: "What we got wrong about hamstring rehab", where: "Stridelab blog", year: "2025" },
      { title: "GPS data on a budget", where: "Stridelab blog", year: "2025" },
      { title: "Notes from a season as an asst", where: "Personal blog", year: "2024" },
    ],
    testimonials: [
      { quote: "Marko reads the literature, talks to the doctors, and still listens to the athletes. Rare combination at 22.", author: "Head sprint coach, AK Crvena Zvezda" },
      { quote: "His U17s ran clean technically and stayed healthy. That's the metric.", author: "Coach S. Petković, AK Crvena Zvezda" },
    ],
    languages: ["Serbian (native)", "English (C1)", "Norwegian (A2)"],
  },

  // Agriculture & Environment
  agri: {
    name: "Ardit Lleshi",
    role: "Bujqësi — viti i fundit",
    faculty: "Fakulteti i Bujqësisë",
    group: "agri",
    school: "Universiteti Bujqësor i Tiranës",
    location: "Korçë, AL",
    pronouns: "he/him",
    tagline: "Soil, olives, and what regenerative practice actually looks like on a small Albanian farm.",
    email: "ardit.lleshi@ubt.edu.al",
    socials: ["instagram/ardit.terra", "linkedin/arditlleshi", "substack/terra-shqipe"],
    now: [
      "Soil testing across 12 farms in the Korça valley",
      "Reading: Wendell Berry, The Unsettling of America",
      "Building a small irrigation rig with two engineering friends",
    ],
    projects: [
      { title: "Terra Shqipe", kind: "Field study", year: "2025", note: "Soil-health survey across 12 smallholder farms. Open data." },
      { title: "Korça Olive Coop", kind: "Consulting", year: "2024", note: "Worked with 4 growers on cover-crop trials." },
      { title: "Drip irrigation rig", kind: "Build", year: "2024", note: "Low-cost rig deployed on three demo plots." },
      { title: "Notes from the Plot", kind: "Newsletter", year: "2024", note: "Monthly read on small-farm practice. 1.4k subs in the Balkans." },
    ],
    experience: [
      { role: "Field researcher", org: "UBT Soil Lab", time: "2024–", note: "Soil sampling, lab analysis, GIS mapping." },
      { role: "Farm assistant", org: "Fattoria Verde, Tuscany", time: "Summer 2025", note: "Eight-week placement, olive harvest + cover crops." },
      { role: "Extension intern", org: "ATTC Korçë", time: "Summer 2024", note: "Worked with growers on water and soil practice." },
    ],
    education: [
      { degree: "BSc Agricultural Sciences", org: "Universiteti Bujqësor i Tiranës", time: "2022–26" },
      { degree: "Erasmus exchange", org: "Università di Pisa", time: "Spring 2025" },
    ],
    skills: ["Soil sampling", "QGIS", "Cover-cropping", "Irrigation design", "R for ecology", "Italian (C1)"],
    awards: [
      { name: "UBT Best Field Project", year: "2025" },
      { name: "Erasmus + Mobility Grant", year: "2025" },
      { name: "Albanian Young Farmer of the Year — runner up", year: "2024" },
    ],
    writing: [
      { title: "Olive groves & cover crops", where: "Notes from the Plot", year: "2025" },
      { title: "Soil tests, every farmer should run them", where: "Notes from the Plot", year: "2025" },
      { title: "A summer in Tuscany", where: "Personal blog", year: "2024" },
    ],
    testimonials: [
      { quote: "Ardit measures things. Then he reads them, then he changes the plan. That is rare and that is good farming.", author: "Prof. L. Stafa, UBT Soil Lab" },
      { quote: "We trialled three of his cover crop mixes. Two are now in the rotation.", author: "Korça Olive Coop, member grower" },
    ],
    languages: ["Albanian (native)", "Italian (C1)", "English (B2)"],
  },
};

// 8 department groups + which faculties they include
const DEPARTMENT_GROUPS = [
  {
    id: "tech",
    name: "Tech & Engineering",
    short: "Tech",
    icon: "⌬",
    accent: "#2d8a4f",
    persona: "developer",
    faculties: [
      "Fakulteti i Shkencave Kompjuterike",
      "Fakulteti i Inxhinierisë Elektrike dhe Kompjuterike",
      "Fakulteti i Inxhinierisë Mekanike",
      "Fakulteti i Ndërtimtarisë",
      "Fakulteti i Arkitekturës",
      "Fakulteti i Telekomunikacionit",
      "Fakulteti i Energjisë",
      "Fakulteti i Mekatronikës",
      "Fakulteti i Shkencave Matematiko-Natyrore",
    ],
  },
  {
    id: "business",
    name: "Business & Management",
    short: "Business",
    icon: "△",
    accent: "#1c4f8a",
    persona: "business",
    faculties: [
      "Fakulteti Ekonomik",
      "Fakulteti i Biznesit",
      "Fakulteti i Menaxhmentit",
      "Fakulteti i Financës dhe Kontabilitetit",
      "Fakulteti i Turizmit dhe Hotelerisë",
      "Fakulteti i Administratës Publike",
    ],
  },
  {
    id: "law",
    name: "Law & Politics",
    short: "Law",
    icon: "§",
    accent: "#5a2a2a",
    persona: "law",
    faculties: [
      "Fakulteti Juridik",
      "Fakulteti i Shkencave Politike",
      "Fakulteti i Marrëdhënieve Ndërkombëtare",
      "Fakulteti i Sigurisë / Kriminologjisë",
    ],
  },
  {
    id: "med",
    name: "Medical & Healthcare",
    short: "Medical",
    icon: "✚",
    accent: "#b03a3a",
    persona: "med",
    faculties: [
      "Fakulteti i Mjekësisë",
      "Fakulteti i Infermierisë",
      "Fakulteti i Stomatologjisë",
      "Fakulteti i Farmacisë",
      "Fakulteti i Radiologjisë",
      "Fakulteti i Veterinarisë",
    ],
  },
  {
    id: "creative",
    name: "Creative & Media",
    short: "Creative",
    icon: "✦",
    accent: "#c44a1f",
    persona: "designer",
    altPersona: "film",
    faculties: [
      "Fakulteti i Arteve",
      "Fakulteti i Muzikës",
      "Fakulteti i Aktrimit / Dramës",
      "Fakulteti i Dizajnit",
      "Fakulteti i Gazetarisë / Komunikimit Masiv",
      "Fakulteti i Media Digjitale / Multimedia",
    ],
  },
  {
    id: "edu",
    name: "Education & Social Sciences",
    short: "Education",
    icon: "❋",
    accent: "#4a3a8a",
    persona: "edu",
    faculties: [
      "Fakulteti i Psikologjisë",
      "Fakulteti Filozofik",
      "Fakulteti Filologjik",
      "Fakulteti i Edukimit",
      "Fakulteti i Shkencave Sociale",
    ],
  },
  {
    id: "sport",
    name: "Sports",
    short: "Sports",
    icon: "◉",
    accent: "#1d6b54",
    persona: "sport",
    faculties: [
      "Fakulteti i Sportit / Kulturës Fizike",
    ],
  },
  {
    id: "agri",
    name: "Agriculture & Environment",
    short: "Agriculture",
    icon: "❀",
    accent: "#5a6a1f",
    persona: "agri",
    faculties: [
      "Fakulteti i Bujqësisë",
      "Fakulteti i Shkencave Mjedisore",
      "Fakulteti i Pyjeve",
    ],
  },
  {
    id: "new",
    name: "New Templates",
    short: "New",
    icon: "★",
    accent: "#f59e0b",
    persona: "sport",
    faculties: [],
  },
];

// Mapping of which template ids fit which department groups.
// Existing 25 are tagged here so each group has options without new templates.
// New department-specific templates (added by templates-f/g/h/i.jsx) extend this.
const TEMPLATE_GROUP_MAP = {
  // existing templates → fit groups
  terminal:    ["tech"],
  editorial:   ["creative", "edu"],
  brutalist:   ["tech", "creative"],
  y2k:         ["creative"],
  swiss:       ["business", "tech"],
  playful:     ["creative", "edu"],
  "3d":        ["tech", "creative"],
  notebook:    ["edu", "creative", "agri"],
  newspaper:   ["business", "law"],
  corporate:   ["tech", "business", "law"],
  boarding:    ["tech", "business"],
  museum:      ["creative"],
  tcg:         ["tech", "sport"],
  manifesto:   ["creative", "edu"],
  atlas:       ["business", "agri", "edu"],
  receipt:     ["business"],
  library:     ["edu", "creative"],
  poster:      ["creative", "sport"],
  finder:      ["tech"],
  botanical:   ["agri", "creative", "med"],
  resume:      ["business", "law", "med", "tech"],
  bento:       ["creative", "tech"],
  notion:      ["business", "edu", "law"],
  spare:       ["creative", "edu"],
  blog:        ["tech", "edu", "creative"],
  // new department-specific templates (26—49)
  blueprint:   ["tech"],
  circuit:     ["tech"],
  specsheet:   ["tech"],
  quarterly:   ["business"],
  bloomberg:   ["business"],
  ledger:      ["business"],
  legalbrief:  ["law", "new"],
  gazette:     ["law", "new"],
  transcript:  ["law", "new"],
  silkiron:    ["law", "new"],
  redacted:    ["law", "new"],
  lexfutura:   ["law", "new"],
  chart:          ["med", "new"],
  anatomy:        ["med", "new"],
  rx:             ["med", "new"],
  vitalsmonitor:  ["med", "new"],
  thelancet:      ["med", "new"],
  pathologylab:   ["med", "new"],
  surgicalbrief:  ["med", "new"],
  nhsclinical:    ["med", "new"],
  magazine:    ["creative"],
  risozine:    ["creative"],
  photofolio:  ["creative"],
  paper:       ["edu"],
  fieldnotes:  ["edu"],
  syllabus:    ["edu"],
  scoreboard:  ["sport", "new"],
  athletecard: ["sport", "new"],
  traininglog: ["sport", "new"],
  fieldjournal: ["agri", "new"],
  almanac:     ["agri", "new"],
  soilmap:     ["agri"],
  // Eupass Standard CV — visible in all departments
  "eupass-classic":   ["tech", "business", "law", "med", "creative", "edu", "sport", "agri"],
  "eupass-modern":    ["tech", "business", "law", "med", "creative", "edu", "sport", "agri"],
  "eupass-minimal":   ["tech", "business", "law", "med", "creative", "edu", "sport", "agri"],
  "eupass-executive": ["tech", "business", "law", "med", "creative", "edu", "sport", "agri"],
  "eupass-fresh":     ["tech", "business", "law", "med", "creative", "edu", "sport", "agri"],
};

// ─── Claude Design personas (exact structure expected by CD templates) ───────
const CD_PERSONAS = {

  // LAW — used by templates-cd-legal-brief, official-gazette, hearing-record
  ewan_kavanagh: {
    key: "ewan_kavanagh",
    name: "Ewan Kavanagh", pronouns: "he/him",
    field: "Law (LLB)", year: "Year 3 of 3",
    institution: "University College London", faculty: "UCL Faculty of Laws",
    specialization: "Constitutional & Human Rights Law",
    currentRole: "Editor-in-Chief, UCL Bentham Law Review",
    location: "London, UK", email: "ewan.kavanagh.22@ucl.ac.uk",
    phone: "+44 7700 900 814", url: "ewan.portfolio-cv.online",
    initials: "EK", barNumber: "PUPIL · LINC. INN · 2026 ENROL.",
    docketNumber: "C-2026-LLB-0142", courtSeat: "Lincoln's Inn",
    tagline: "Reasoning that stays standing on its third reading.",
    summary: "Final-year LLB at UCL focused on the boundary between Parliament and the Convention. Editor of the Bentham Law Review; eight competitive moots in three years; pupillage applications under way.",
    mooting: [
      { name: "ELSA Moot Court — WTO", role: "Counsel", outcome: "Semi-final · European round", year: 2025 },
      { name: "Philip C. Jessup International", role: "First speaker", outcome: "Regional winner · Best Memorial (R)", year: 2025 },
      { name: "Telders International Law", role: "Counsel", outcome: "Quarter-final", year: 2024 },
      { name: "OUP Constitutional Moot", role: "Counsel · Appellant", outcome: "Winner", year: 2024 },
      { name: "Inner Temple Lawson Moot", role: "Junior counsel", outcome: "Finalist", year: 2023 },
      { name: "UCL Internal Mooting Cup", role: "Counsel", outcome: "Winner · Best speaker", year: 2023 },
    ],
    publications: [
      { title: "Reading Adams: a constitutional answer in search of its question", venue: "UCL Bentham Law Review · Vol XXXII", role: "Case note", year: 2024, pages: "pp. 144 — 161" },
      { title: "Strasbourg in retreat? Margin-of-appreciation after Verein KlimaSeniorinnen", venue: "European Human Rights Law Review", role: "Co-author", year: 2025, pages: "pp. 22 — 37" },
      { title: "Editor's note · the rule-of-law issue", venue: "UCL Bentham Law Review · Vol XXXIII", role: "Editor-in-Chief", year: 2025, pages: "p. iii" },
      { title: "Two cheers for declaratory relief", venue: "Verfassungsblog (student column)", role: "Contributor", year: 2024, pages: "online" },
      { title: "Habeas in the digital age (student gazette)", venue: "UCL Law Society Gazette", role: "Author", year: 2023, pages: "pp. 8 — 9" },
    ],
    experience: [
      { role: "Vacation Scheme", org: "Mishcon de Reya LLP · Dispute Resolution", period: "Jul 2025", bullets: [ "Bundled and chronologised disclosure for £18m commercial fraud claim.", "Drafted memo on s.32 LAct 1980 — adopted into client letter." ] },
      { role: "Legal Intern", org: "Liberty (The National Council for Civil Liberties)", period: "Jun — Aug 2024", bullets: [ "Public Order Act response brief, cited in JCHR submission.", "Casework support for stop-and-search judicial review." ] },
      { role: "Visiting Researcher", org: "European Court of Human Rights · Strasbourg", period: "Apr — May 2024", bullets: [ "Assisted Article 8 case-law digest for Section II Registry.", "Supervised by Dr A. Petrova." ] },
      { role: "Pro Bono Caseworker", org: "UCL Law Clinic · Housing rota", period: "2023 — present", bullets: [ "75+ pro bono hours; second-line file review.", "First-instance possession defence drafted with supervisor." ] },
      { role: "Court Marshal", org: "Royal Courts of Justice · Hon. Mr Justice Hayden", period: "Easter 2023", bullets: [ "Two weeks shadow; bench notes on Court of Protection list." ] },
    ],
    education: [
      { degree: "LLB (Hons) Law", org: "University College London · Faculty of Laws", period: "2022 — 26", notes: "Predicted First. Modules: Constitutional, HR, Jurisprudence, Public International, Conflict of Laws." },
      { degree: "Erasmus+ Exchange Semester", org: "Sciences Po Paris · Law School", period: "Spring 2024", notes: "Coursework: Comparative Constitutional Law, French Public Law (taught in French)." },
      { degree: "A-Levels · History · French · English Lit · Latin", org: "King Edward's School, Birmingham", period: "2017 — 22", notes: "A*A*A*A. Head Boy. Debating Cup winner." },
    ],
    languages: [
      { name: "English", level: "Native", cefr: "C2" },
      { name: "French", level: "Advanced", cefr: "C1" },
      { name: "German", level: "Upper-Intermediate", cefr: "B2" },
      { name: "Latin", level: "Reading proficiency", cefr: "—" },
    ],
    awards: [
      { name: "Hardwicke Entrance Scholarship", org: "Lincoln's Inn", year: "2022" },
      { name: "Faculty Prize · Constitutional Law", org: "UCL Faculty of Laws", year: "2024" },
      { name: "Best Memorial · Regional Round", org: "Jessup ILSA", year: "2025" },
      { name: "Sir John Foster Bursary", org: "UCL Faculty of Laws", year: "2024" },
    ],
    activities: [
      "Editor-in-Chief, UCL Bentham Law Review (2025/26).",
      "Moots Officer, UCL Law Society (2024/25).",
      "Pupillage scout, Garden Court Chambers Open Day delegate.",
      "Volunteer reader, Talking Newspaper for the Blind, Lambeth.",
    ],
  },

  // MEDICAL — used by templates-cd-patient-chart, anatomical-plate, rx-prescription
  eve_hartwell: {
    key: "eve_hartwell",
    name: "Eve Hartwell", pronouns: "she/her",
    field: "Medicine (MBChB)", year: "Year 5 of 6",
    institution: "University of Edinburgh", faculty: "Edinburgh Medical School",
    specialization: "Internal Medicine · Neurology interest",
    currentRole: "Final-year clinical, Royal Infirmary of Edinburgh",
    location: "Edinburgh, UK", email: "eve.hartwell@ed.ac.uk",
    phone: "+44 7700 900 226", url: "eve.portfolio-cv.online",
    mrn: "MBChB-2026-0431", dob: "04 Sep 2001", initials: "EH",
    nhsNumber: "443 207 1188",
    tagline: "Quiet hands. Clean handover. Curious about brains.",
    summary: "Final-year medical student aiming at IMT then neurology. I run audits the wards actually use, scrub in when invited, and I am reliably the one who finds the missing chart.",
    rotations: [
      { service: "Cardiology", site: "Royal Infirmary of Edinburgh", period: "Sep — Nov 2025", weeks: 8, lead: "Dr A. Mackay", procedures: "ECG x40, TTE assist x12, cardioversion observed x3" },
      { service: "Acute Medicine", site: "Western General Hospital", period: "Jun — Aug 2025", weeks: 8, lead: "Dr P. Singh", procedures: "ABG x18, cannulation x60, NG insertion x4" },
      { service: "Neurology", site: "Western General · NSU", period: "Mar — May 2025", weeks: 8, lead: "Prof. C. Innes", procedures: "Lumbar puncture x2, NIHSS scoring trained, OPD x90" },
      { service: "General Practice", site: "Borders GP, Galashiels", period: "Jan — Feb 2025", weeks: 6, lead: "Dr H. McKenzie", procedures: "Solo consults x40 (supervised)" },
      { service: "Obstetrics & Gynaecology", site: "Royal Infirmary, Simpson Centre", period: "Oct — Dec 2024", weeks: 8, lead: "Mr R. Patel", procedures: "Deliveries observed x12, assist x4" },
      { service: "Emergency Department", site: "RIE A&E", period: "Aug — Sep 2024", weeks: 4, lead: "Dr S. Forbes", procedures: "Triage shadow x14 shifts, suturing x6, plaster x3" },
    ],
    research: [
      { title: "Diffusion-MRI biomarkers in early Parkinson's disease", venue: "European Journal of Neurology", status: "Published", role: "Second author", year: 2025, ds: "n=86, Bayesian mixed models" },
      { title: "Validation of a 6-item dementia screening tool in Lothian primary care", venue: "BJGP Open", status: "Under review", role: "First author", year: 2026, ds: "n=312, multi-site GP audit" },
      { title: "COVID-19 long-term cognitive outcomes audit", venue: "NHS Lothian · Internal audit", status: "Closed loop", role: "Lead auditor", year: 2024, ds: "n=148" },
      { title: "MBChB Honours Project: stroke imaging biomarker pipeline", venue: "Edinburgh MBChB · BMedSci Year", status: "Awarded First", role: "Author", year: 2024, ds: "—" },
    ],
    skills: {
      clinical: [
        { name: "ECG interpretation", level: "Confident" },
        { name: "Venous cannulation", level: "Independent" },
        { name: "Arterial blood gas", level: "Independent" },
        { name: "Suturing — simple interrupted, mattress", level: "Independent" },
        { name: "BLS / ILS Provider", level: "Certified" },
        { name: "NG tube insertion", level: "Supervised" },
        { name: "Male catheterisation", level: "Independent" },
        { name: "Lumbar puncture", level: "Supervised x2" },
        { name: "NIHSS scoring", level: "Trained" },
      ],
      software: [
        { name: "STATA", level: 4 }, { name: "R · ggplot2, lme4", level: 4 },
        { name: "REDCap", level: 5 }, { name: "EPR / TRAK", level: 5 },
        { name: "EndNote", level: 4 }, { name: "Python · imaging (nibabel)", level: 3 },
      ],
    },
    education: [
      { degree: "MBChB Medicine", org: "University of Edinburgh", period: "2021 — 27", notes: "Honours year (BMedSci): First class. Distinction in Anatomy." },
      { degree: "BMedSci (Hons) Neuroscience", org: "University of Edinburgh", period: "2023 — 24", notes: "Awarded First. Thesis: diffusion-MRI biomarkers in PD." },
      { degree: "Higher · Bio · Chem · Maths · English · German", org: "George Watson's College, Edinburgh", period: "2015 — 21", notes: "AAAAA. Head of Debating Society." },
    ],
    awards: [
      { name: "Dean's List", org: "Edinburgh Medical School", year: "2023 · 2024 · 2025" },
      { name: "Wellcome Vacation Scholarship", org: "Wellcome Trust", year: "2024" },
      { name: "Anatomy Prize · Distinction", org: "Edinburgh Med School", year: "2022" },
      { name: "RCSEd Student Surgical Society Bursary", org: "RCSEd", year: "2024" },
    ],
    languages: [
      { name: "English", level: "Native", cefr: "C2" },
      { name: "German", level: "Upper-Intermediate", cefr: "B2" },
      { name: "Latin", level: "Reading", cefr: "B1" },
    ],
    extras: [
      "Edinburgh Medic-Mentor — pairs Year-1 students with clinical years.",
      "RCSEd Student Surgical Society · committee, suturing-workshop lead.",
      "Volunteer phlebotomist · St John Scotland.",
    ],
    vitals: { bp: "118/74", hr: "62", rr: "14", spo2: "99%", temp: "36.8 °C" },
    allergies: ["Penicillin — rash, age 9. Documented."],
  },

  // AGRICULTURE — used by templates-cd-field-journal, harvest-almanac
  adam_lyle: {
    key: "adam_lyle",
    name: "Adam Lyle", pronouns: "he/him",
    field: "Agriculture (BSc Hons)", year: "BSc · Final Year",
    institution: "Harper Adams University", faculty: "School of Sustainable Food and Farming",
    specialization: "Soil Science · Sustainable Agronomy",
    currentRole: "Final-year placement · Soil Survey, James Hutton Institute",
    location: "Newport, Shropshire, UK", email: "a.lyle@harper-adams.ac.uk",
    phone: "+44 7700 900 358", url: "adam.portfolio-cv.online",
    initials: "AL", dob: "22 Feb 2002",
    tagline: "Boots muddy, spreadsheets clean.",
    summary: "Final-year agriculture student specialising in soil. I sample, sieve, and model — then write farmer-readable summaries. Looking for soil-science roles in extension or research.",
    fields: [
      { name: "North Shropshire rotation audit", loc: "Whitchurch, Shrop.", crop: "Potato / W. wheat / OSR", ha: 220, methods: "60 cores, P/K/pH grid, Mehlich-3", year: 2025, outcome: "VRA map adopted by farm; −18% N-use." },
      { name: "Lincolnshire cover-crop trial", loc: "Stamford, Lincs.", crop: "Cover-crop mixes", ha: 40, methods: "Replicated plots, NDVI + soil-respiration", year: "2024 — 25", outcome: "+0.4% SOM in 14 months." },
      { name: "Cypriot olive irrigation design", loc: "Lefkosia, CY", crop: "Olea europaea", ha: 12, methods: "RTK survey, CROPWAT model", year: 2024, outcome: "Drip layout commissioned; water −31%." },
      { name: "Welsh upland grassland survey", loc: "Mid-Wales", crop: "Grassland · grazing", ha: 1200, methods: "BSV quadrats, soil pH, OM%, GIS layering", year: 2023, outcome: "Baseline dataset for ELMS application." },
      { name: "Family dairy farm — soil-fertility plan", loc: "Carmarthenshire, Wales", crop: "Grass · maize silage", ha: 95, methods: "Whole-farm sampling, FYM mass balance", year: "2021 — present", outcome: "Slurry application capped; rye-grass yield +8%." },
    ],
    research: [
      { title: "Soil carbon stocks under min-till in heavy clay soils of the West Midlands", venue: "Harper Adams · BSc Dissertation", status: "In progress", role: "Author · Supv: Dr H. Atherton", year: 2026 },
      { title: "Nitrogen-use efficiency in mixed cover-crop rotations", venue: "European Journal of Agronomy", status: "Submitted", role: "Co-author (3rd)", year: 2026 },
      { title: "Soil microbiome dataset · WCS pilot", venue: "Wageningen ESS · open repository", status: "Published", role: "Data steward", year: 2024 },
    ],
    experience: [
      { role: "Soil Survey Placement", org: "James Hutton Institute · Aberdeen", period: "Sep 2025 — Aug 2026", bullets: [ "Field sampling NE Scotland (200+ cores).", "QGIS layering for Scottish soil information system." ] },
      { role: "AHDB Extension Intern", org: "Agriculture & Horticulture Development Board", period: "Summer 2024", bullets: [ "On-farm visits across 4 counties; farmer-readable summaries.", "Authored two AHDB field-walk briefings." ] },
      { role: "Summer Researcher", org: "AB Agri · Cambridge", period: "Summer 2023", bullets: [ "Trial data cleaning, R scripts for plot-mean separation.", "Cover-crop plot establishment." ] },
      { role: "Farm hand", org: "Family dairy farm, Carmarthenshire", period: "2014 — present", bullets: [ "Whole rotation, calving cover, kit maintenance.", "Holiday + lambing weekends." ] },
    ],
    skills: {
      tech: [
        { name: "QGIS · vector + raster", level: 5 },
        { name: "R · ecology (vegan, lme4)", level: 4 },
        { name: "Soil sampling · BS3882 / WCS", level: 5 },
        { name: "Mehlich-3 + olsen-P prep", level: 4 },
        { name: "Irrigation design · CROPWAT", level: 4 },
        { name: "RTK survey (Trimble R10)", level: 4 },
        { name: "Drone NDVI · DJI P4 Multi", level: 3 },
        { name: "Python · pandas (light)", level: 3 },
      ],
      practical: [
        "Whole-farm fertility planning · RB209",
        "Slurry / FYM mass balance",
        "Cover-crop mix specification",
        "Min-till + strip-till operation",
        "ELMS / SFI scheme application support",
        "Telehandler · cat. C+E provisional",
        "Pesticide application — PA1, PA2A, PA6",
      ],
    },
    education: [
      { degree: "BSc (Hons) Agriculture · Soil Science pathway", org: "Harper Adams University", period: "2022 — 26", notes: "Sandwich year placed at James Hutton. Dissertation: SOC under min-till." },
      { degree: "Exchange Semester · Wageningen ESS", org: "Wageningen University & Research, NL", period: "Spring 2024", notes: "Soil chemistry, ecology, GIS modules." },
      { degree: "BTEC Ext. Diploma · Agriculture", org: "Coleg Sir Gâr, Carmarthenshire", period: "2020 — 22", notes: "DDD. NPTC PA1/PA2A. Young Farmer of the Year, county." },
    ],
    publications: [
      { title: "Cover-cropping in clay loams: a practical field-walk briefing", venue: "AHDB Field Briefing 24-07", year: 2024 },
      { title: "Newsletter · 'Soil Tin' · monthly", venue: "Substack · 614 subs", year: "2023 — present" },
      { title: "Twitter/X thread · cover-crop establishment costs (12k views)", venue: "@adam_lyle_soil", year: 2024 },
    ],
    languages: [
      { name: "English", level: "Native", cefr: "C2" },
      { name: "Welsh", level: "Conversational", cefr: "B1" },
      { name: "Dutch", level: "Basic", cefr: "A2" },
    ],
    awards: [
      { name: "Harper Adams Soil Science Prize", org: "Harper Adams University", year: "2024" },
      { name: "Nuffield Farming Scholarship (nominee)", org: "Nuffield", year: "2025" },
      { name: "Young Farmer of the Year · county", org: "YFC Carmarthenshire", year: "2022" },
    ],
  },

  // SPORTS — used by templates-sport-t44 (Scoreboard), templates-sport-t45 (Athlete Card), templates-cd-training-log
  mark_holloway: {
    key: "mark_holloway",
    name: "Mark Holloway", pronouns: "he/him",
    field: "Sport & Exercise Science (BSc)", year: "Year 3 of 3",
    institution: "Loughborough University", faculty: "School of Sport, Exercise and Health Sciences",
    specialization: "Performance Analysis · Strength & Conditioning",
    currentRole: "Academy Performance Analyst · Nottingham Forest U23",
    location: "Loughborough, UK", email: "m.holloway@lboro.ac.uk",
    phone: "+44 7700 900 473", url: "mark.portfolio-cv.online",
    initials: "MH", dob: "11 Mar 2003",
    height: "6 ft 1 in / 185 cm", weight: "82 kg",
    season: "2025/26", sportPlayed: "Association Football (GK)",
    tagline: "Data that coaches actually open.",
    summary: "Final-year Sport & Exercise Science student at Loughborough. I build performance dashboards elite coaches use, publish load-monitoring research, and hold FA Level 2. Looking for graduate analyst or S&C roles in football or multi-sport.",
    headlineStats: [
      { value: "3", label: "seasons analysed" },
      { value: "120+", label: "match reports" },
      { value: "4.2", label: "GPA equivalent" },
      { value: "2", label: "publications" },
    ],
    coached: [
      { squad: "Nottingham Forest U23", role: "Performance Analyst", period: "Sep 2025 — present", result: "East Midlands Youth League · 3rd", load: "GPS · Catapult Vector", n: 22, outcomes: [{ stat: "+12%", label: "high-speed running output vs baseline" }, { stat: "−0.4", label: "ACWR — injury risk down" }] },
      { squad: "Loughborough FC First", role: "Volunteer Analyst", period: "2024/25", result: "Midland Alliance · 4th", load: "Notational + video", n: 18, outcomes: [{ stat: "120+", label: "match reports delivered on time" }, { stat: "+8%", label: "set-piece success rate" }] },
      { squad: "Loughborough University 1st XI", role: "S&C Assistant", period: "2023/24", result: "BUCS Premier North · Runners-up", load: "RPE + wellbeing", n: 26, outcomes: [{ stat: "0", label: "soft-tissue injuries in 12-week block" }, { stat: "+6%", label: "CMJ height improvement" }] },
      { squad: "Leicester City Foundation U16", role: "Placement S&C", period: "Summer 2024", result: "Academy Cup · Semi-final", load: "Manual load metrics", n: 16, outcomes: [{ stat: "4", label: "IDPs written, all adopted by coach" }, { stat: "+9%", label: "sprint speed 30 m end-of-block" }] },
    ],
    research: [
      { title: "Acute:chronic workload ratio and soft-tissue injury in U23 football: a prospective cohort", venue: "Journal of Sports Sciences", status: "Under review", role: "First author", year: 2026, ds: "n=44, 34 weeks" },
      { title: "GPS-derived high-speed running thresholds in youth academy football", venue: "Loughborough BSc Dissertation", status: "In progress", role: "Author · Supv: Dr K. Murray", year: 2026, ds: "—" },
      { title: "Validity of sRPE vs GPS total distance in sub-elite football", venue: "Loughborough Undergraduate Research Symposium", status: "Presented", role: "Author", year: 2025, ds: "n=18, 12 weeks" },
    ],
    skills: {
      tech: [
        { name: "Catapult Vector · GPS", level: 5 },
        { name: "Tableau · dashboards", level: 4 },
        { name: "R · mixed models, ggplot2", level: 4 },
        { name: "Python · pandas, matplotlib", level: 3 },
        { name: "Hudl Sportscode · tagging", level: 5 },
        { name: "Microsoft Power BI", level: 3 },
        { name: "SPSS", level: 4 },
        { name: "VO₂max + isokinetic testing", level: 4 },
      ],
      practical: [
        "GPS load monitoring · acute:chronic ratio",
        "Match video tagging · Hudl Sportscode",
        "Performance dashboard design",
        "Strength testing · 1RM, CMJ, sprint 10/30 m",
        "Individual development plan (IDP) authoring",
        "Sports massage — ITEC Level 3",
      ],
    },
    certs: [
      { name: "FA Level 2 Coaching Licence", body: "The Football Association", status: "Active", year: 2024 },
      { name: "UKSCA Strength & Conditioning", body: "UK Strength & Conditioning Assoc.", status: "Candidate 2026", year: 2026 },
      { name: "First Aid · FA Emergency", body: "St John Ambulance / The FA", status: "Active", year: 2025 },
      { name: "ITEC Sports Massage Level 3", body: "ITEC Qualifications", status: "Active", year: 2024 },
      { name: "Catapult Vector Operator", body: "Catapult Sports", status: "Certified", year: 2025 },
      { name: "BWF Futsal Badge", body: "British Wheelchair Football", status: "Active", year: 2023 },
    ],
    media: [
      { kind: "Podcast", name: "The Analyst Room — Ep. 14" },
      { kind: "Article", name: "Lboro Sport Science Review" },
      { kind: "Video", name: "Catapult GPS Workflow Demo" },
    ],
    experience: [
      { role: "Performance Analyst", org: "Nottingham Forest U23 · Academy", period: "Sep 2025 — present", bullets: [ "GPS Catapult Vector load monitoring for 22-player squad.", "Weekly PDF dash delivered to head coach before every fixture." ] },
      { role: "BSc Placement — S&C", org: "Leicester City Foundation", period: "Summer 2024", bullets: [ "Resistance-session delivery for U16 academy; RPE tracking.", "IDP written for 4 players flagged at end-of-season review." ] },
      { role: "Volunteer Analyst", org: "Loughborough FC First Team", period: "2024/25", bullets: [ "Full-season notational analysis + post-match video clips.", "Presented findings to manager in weekly debrief." ] },
    ],
    education: [
      { degree: "BSc (Hons) Sport & Exercise Science", org: "Loughborough University · SSEHS", period: "2022 — 26", notes: "Predicted First. Modules: Biomechanics, Performance Analysis, Strength & Conditioning, Research Methods." },
      { degree: "Erasmus+ Sport Science Exchange", org: "KU Leuven · Faculty of Movement and Rehabilitation Sciences", period: "Spring 2025", notes: "Sport physiology, load management, Dutch language module." },
      { degree: "A-Levels · PE · Biology · Maths", org: "Becket School, Nottingham", period: "2019 — 22", notes: "A*AA. Head of Sport. County cross-country champion." },
    ],
    languages: [
      { name: "English", level: "Native", cefr: "C2" },
      { name: "Dutch", level: "Elementary", cefr: "A2" },
    ],
    awards: [
      { name: "Loughborough Dean's Scholarship", org: "Loughborough University", year: "2022" },
      { name: "BASES Undergraduate Research Award — shortlisted", org: "BASES", year: "2025" },
      { name: "County Cross-Country Champion U20", org: "Nottinghamshire AA", year: "2021" },
    ],
    activities: [
      "Loughborough Sport Science Society — committee member.",
      "BUCS football player (GK) — Loughborough 1st XI.",
      "Volunteer coach — Notts County Foundation Saturday club.",
    ],
  },
};

if (typeof window !== "undefined") {
  if (window.PERSONAS) {
    Object.assign(window.PERSONAS, NEW_PERSONAS, CD_PERSONAS);
  } else {
    window.PERSONAS = { ...NEW_PERSONAS, ...CD_PERSONAS };
  }
  window.DEPARTMENT_GROUPS = DEPARTMENT_GROUPS;
  window.TEMPLATE_GROUP_MAP = TEMPLATE_GROUP_MAP;
}
