'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

import {
  FACULTY_FILTERS,
  TEMPLATE_CATALOG,
  type FacultyGroup,
  type TemplateCatalogItem,
} from '@/lib/templateCatalog'

import styles from './page.module.css'

type FilterValue = 'all' | FacultyGroup

/**
 * Static, pre-rendered preview image of the real template page. Generated by
 * scripts/gen-thumbs.mjs into public/template-thumbs/<slug>.webp. Loads
 * instantly (just an image) instead of booting a live React+Babel iframe.
 */
function TemplatePreview({ template }: { template: TemplateCatalogItem }) {
  return (
    <div className={styles.preview} style={{ padding: 0, overflow: 'hidden' }}>
      {/* Browser chrome dots */}
      <div style={{
        display: 'flex', gap: 5, padding: '8px 10px',
        background: 'rgba(0,0,0,.04)',
        borderBottom: '1px solid rgba(0,0,0,.07)',
        flexShrink: 0,
      }}>
        <span style={{ width: 8, height: 8, borderRadius: '50%', background: 'rgba(0,0,0,.18)' }} />
        <span style={{ width: 8, height: 8, borderRadius: '50%', background: 'rgba(0,0,0,.18)' }} />
        <span style={{ width: 8, height: 8, borderRadius: '50%', background: 'rgba(0,0,0,.18)' }} />
      </div>
      {/* Pre-rendered image — fills remaining height, anchored to the top */}
      <div style={{ flex: 1, overflow: 'hidden', position: 'relative', background: '#fff' }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={`/template-thumbs/${template.slug}.webp`}
          alt={`${template.name} template preview`}
          loading="lazy"
          decoding="async"
          style={{
            position: 'absolute',
            inset: 0,
            width: '100%',
            height: '100%',
            objectFit: 'cover',
            objectPosition: 'top center',
          }}
        />
      </div>
      {/* Bottom meta strip */}
      <div className={styles.previewFooter} style={{ padding: '7px 12px' }}>
        <span>{template.tone}</span>
        <b>{template.groups[0]}</b>
      </div>
    </div>
  )
}

export default function TemplateChooser({ activeSlugs }: { activeSlugs?: string[] }) {
  const router = useRouter()
  const [filter, setFilter] = useState<FilterValue>('all')
  const [selectedSlug, setSelectedSlug] = useState('')
  const [message, setMessage] = useState('')

  // Only show templates the admin has marked active in the DB. If the DB
  // returned nothing (empty/unseeded), fall back to the full code catalog.
  const catalog = useMemo(() => {
    if (!activeSlugs || activeSlugs.length === 0) return TEMPLATE_CATALOG
    const active = new Set(activeSlugs)
    return TEMPLATE_CATALOG.filter((template) => active.has(template.slug))
  }, [activeSlugs])

  const templates = useMemo(() => {
    if (filter === 'all') return catalog
    return catalog.filter((template) => template.groups.includes(filter))
  }, [filter, catalog])

  function countForFilter(value: FilterValue) {
    if (value === 'all') return catalog.length
    return catalog.filter((template) => template.groups.includes(value)).length
  }

  async function chooseTemplate(slug: string) {
    setSelectedSlug(slug)
    setMessage('')

    try {
      const res = await fetch('/api/select-template', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({ slug }),
      })

      if (res.status === 401) {
        router.push(`/signup?template=${slug}`)
        return
      }

      const data = await res.json()

      if (!res.ok) {
        setMessage(data.error || 'Could not select this template.')
        return
      }

      router.push(data.redirect || `/dashboard?template=${slug}`)
      router.refresh()
    } catch {
      setMessage('Could not select this template. Please try again.')
    } finally {
      setSelectedSlug('')
    }
  }

  return (
    <>
      <div className={styles.toolbar}>
        <div className={styles.filterGroup} aria-label="Filter templates by faculty group">
          {FACULTY_FILTERS.map((item) => (
            <button
              key={item.value}
              type="button"
              className={`${styles.filterButton} ${filter === item.value ? styles.activeFilter : ''}`}
              onClick={() => setFilter(item.value)}
            >
              {item.label}
              <span>{countForFilter(item.value)}</span>
            </button>
          ))}
        </div>
      </div>

      {message && <p className={styles.message}>{message}</p>}

      <div className={styles.grid}>
        {templates.map((template) => (
          <article key={template.slug} className={styles.card}>
            <TemplatePreview template={template} />
            <div className={styles.cardBody}>
              <div className={styles.cardMeta}>
                <span>{template.groupLabel}</span>
                <b>{template.tone}</b>
              </div>
              <h2>{template.name}</h2>
              <p>{template.description}</p>
              <div className={styles.bestFor}>{template.bestFor}</div>
              <div className={styles.sections}>
                {template.sections.map((section) => (
                  <span key={section}>{section}</span>
                ))}
              </div>
              <div className={styles.cardActions}>
                <Link
                  href={`/templates/${template.slug}/preview`}
                  className={styles.previewButton}
                >
                  Preview
                </Link>
                <button
                  type="button"
                  className={styles.chooseButton}
                  disabled={selectedSlug === template.slug}
                  onClick={() => chooseTemplate(template.slug)}
                >
                  {selectedSlug === template.slug ? 'Selecting...' : 'Choose'}
                </button>
              </div>
            </div>
          </article>
        ))}
      </div>
    </>
  )
}
